apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etcd-client
  template:
    metadata:
      labels:
        app: etcd-client
    spec:
      containers:
      - name: etcd-client
        image: us-central1-docker.pkg.dev/molten-verve-216720/$TENANT/etcd-client:k8s
        # The client containers must be kept running for Antithesis to keep testing
        command: ["sleep"]
        args: ["infinity"]
